### ISSUE TITLE
Downloadable release?

### ISSUE THREAD

**Issue by dgattey** [johnno1962/RefactoratorApp#2]
Is there any way you could release versions so we could download them instead of having to build locally?

**Comment by johnno1962** [comment]
It mentions in the readme there is a downloadable version if you follow the link: http://johnholdsworth.com/refactorator.html

**Comment by dgattey** [comment]
Sorry, my bad. All I saw was "Help is available here" and stopped reading that sentence. Maybe start the sentence with that instead
