### ISSUE TITLE
Auto app update

### ISSUE THREAD

**Issue by pmusolino** [johnno1962/RefactoratorApp#3]
First of all, great idea, Refactorator is really cool!

Then, i suggest to implement (if possible) an autoupdate engine of Refactorator, in this way the app is always up to date. :)

**Comment by johnno1962** [comment]
Fair point, I’ve pushed a simple upgrade check if you’d like to review it for me:

https://github.com/johnno1962/RefactoratorApp/commit/e5caa8d8ed9b5aaf9bed60b0c2a5c7ab89e1adca?diff=unified
