### ISSUE TITLE
GraphViz export

### ISSUE THREAD

**Issue by DivineDominion** [johnno1962/RefactoratorApp#4]
Would be cool if you ported the GraphViz export to visualize dependencies

**Comment by johnno1962** [comment]
Ha! just working on that as it happens. Watch this space.

**Comment by johnno1962** [comment]
I’ve uploaded a new version with dependencies graphs if you want to give it a try. http://johnholdsworth.com/Refactorator.app.zip

It’s File/Dependencies.. Realy only useful for modestly sized projects.

**Comment by johnno1962** [comment]
After a bit of drama pushing the the file the new version supporting “File/Dependencies” is available:
http://johnholdsworth.com/refactorator.html

**Comment by DivineDominion** [comment]
Very cool! I wonder if the Xcode DB allows to focus on the app target so not every teeny outgoing library dependency and incoming test case dependency is shown. But works well out of the box already!

**Comment by johnno1962** [comment]
How do you mean? It should exclude Pods and system libraries already. Not sure how I'd exclude tests. A simple filename pattern?

**Comment by DivineDominion** [comment]
I was thinking about limiting the scope to project targets. In Swift terms, this equals modules. So that I can see dependencies inside the defining module and maybe 1 level into other modules, but not the dependencies in there. This should get rid of test--production code dependencies (when I look at the production code, that is).
