### ISSUE TITLE
"Dependencies" without graphviz installed produces:  »“Download_macos.php” can’t be found.«

### ISSUE THREAD

**Issue by DivineDominion** [johnno1962/RefactoratorApp#6]
After the info alert that "dot" needs to be installed, another alert pops up with the Finder icon, saying:

> “Download_macos.php” can’t be found.

It seems the PHP [URL String doesn't work](https://github.com/johnno1962/RefactoratorApp/blob/285302da7a6eaba97ce0df9cc57ad5e353034d13/Refactorator/AppController.swift#L72). Maybe constructing a URL directly can help, or the php file extension isn't recognized by NSWorkspace.

![screen shot 2016-12-15 at 14 36 42](https://cloud.githubusercontent.com/assets/59080/21226158/8d916f24-c2d4-11e6-9671-6d90bc6b8874.png)

**Comment by johnno1962** [comment]
This was just a silly bug in converting to a URL. Can you download a try now?
