### ISSUE TITLE
Some source code files are missing

### ISSUE THREAD

**Issue by dmitriyl** [johnno1962/RefactoratorApp#9]
SKApi.swift that used in Formatter.swift.
Where can I find it?

**Comment by johnno1962** [comment]
https://github.com/johnno1962/Refactorator/blob/master/refactord/SourceKit.swift#L169
Thanks to: https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/library_wrapper_sourcekitd.swift

**Comment by dmitriyl** [comment]
I can not find SKApi in that repository either. Is it some kid of wrapper around SourceKit? Should it be a separated class?

**Comment by johnno1962** [comment]
It was added at the last minute.. https://github.com/johnno1962/Refactorator/blob/master/refactord/SourceKit.swift#L99

**Comment by dmitriyl** [comment]
Thank you!
